export const ROUTES = {
  MAP: {
    DEFAULT: '/api/map',
    GET_INFO: '/get-info',
    GET_CITY_MARKERS: '/get-city-markers',
    ADD_CITY_MARKER: '/add-city-marker',
    EDIT_CITY_MARKER: '/edit-city-marker/:id',
    DELETE_CITY_MARKER: '/delete-city-marker/:id',
    GET_ALL_MEMORIALS: '/get-memorial-markers',
    GET_ALL_MEMORIAL_TYPES: '/get-memorial-types',
    ADD_MEMORIAL_MARKER: '/add-memorial-marker',
    DELETE_MEMORIAL_MARKER: '/delete-memorial/:id',
    GET_MEMORIAL: '/get-memorial/:id',
    EDIT_MEMORIAL: '/edit-memorial-marker/:id',
    ADD_MEMORIAL_TYPE: '/add-memorial-type',
    EDIT_MEMORIAL_TYPE: '/edit-memorial-type/:id',
    DELETE_MEMORIAL_TYPE: '/delete-memorial-type/:id',
  },
  PUBLICATION: {
    DEFAULT: '/api/publication',
    ADD: '/add',
    GET: '/get',
    GET_CURRENT: '/get/:id',
    GET_ALL: '/get-all',
    GET_FAVORITE: '/get-favorite',
    GET_RECENT: '/get-recent',
    DELETE: '/delete/:id',
    EDIT: '/edit/:id',
    SET_FAVORITE: '/set-favorite/:id',
    REMOVE_FAVORITE: '/remove-favorite/:id',
  },
  AUTH: {
    DEFAULT: '/api/auth',
    LOGIN: '/login',
    LOGOUT: '/logout',
    REFRESH: '/refresh',
  },
};
