export const PUBLICATION = {
  ADD_PUBLICATION: 'ADD_PUBLICATION',
  GET_ALL_PUBLICATION: 'GET_ALL_PUBLICATIONS',
  ADD_PUBLICATIONS_LIMIT: 'ADD_PUBLICATIONS_LIMIT',
  GET_FAVORITE_PUBLICATION: 'GET_FAVORITE_PUBLICATIONS',
  GET_PUBLICATION_BY_TITLE: 'GET_PUBLICATIONS_BY_TITLE',
};
