export const INTERVIEW = {
  GET_ALL_INTERVIEW: 'GET_ALL_INTERVIEW',
  GET_FAVORITE_INTERVIEW: 'GET_FAVORITE_INTERVIEW',
  GET_INTERVIEWS_BY_TITLE: 'GET_INTERVIEWS_BY_TITLE',
};

export const PUBLICATION = {
  ADD_PUBLICATION: 'ADD_PUBLICATION',
};
