export const INTERVIEW = {
  ADD_INTERVIEW: 'ADD_INTERVIEW',
  GET_ALL_INTERVIEW: 'GET_ALL_INTERVIEW',
  GET_FAVORITE_INTERVIEW: 'GET_FAVORITE_INTERVIEW',
  GET_INTERVIEWS_BY_TITLE: 'GET_INTERVIEWS_BY_TITLE',
};
