export const ERRORS = {
  USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNDEFINED_TOKEN: 'UNDEFINED_TOKEN',
  NO_ACCESS: 'NO_ACCESS',
  INVALID_DATA: 'INVALID_DATA',
  WRONG_LOGIN_PASSWORD: 'WRONG_LOGIN_PASSWORD',
};
