export const ERRORS = {
  NO_ACCESS: 'NO_ACCESS',
  INVALID_DATA: 'INVALID_DATA',
};

export const AUTH_ERRORS = {
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNDEFINED_TOKEN: 'UNDEFINED_TOKEN',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  WRONG_LOGIN_PASSWORD: 'WRONG_LOGIN_PASSWORD',
};
