export const ROUTES = {
  MAP: {
    GET_INFO: 'api/map/get-info',
    GET_CITY_MARKERS: 'api/map/get-city-markers',
    ADD_CITY_MARKER: 'api/map/add-city-marker',
    EDIT_CITY_MARKER: 'api/map/edit-city-marker',
    DELETE_CITY_MARKER: 'api/map/delete-city-marker',
    GET_ALL_MEMORIALS: 'api/map/get-memorial-markers',
    GET_ALL_MEMORIAL_TYPES: 'api/map/get-memorial-types',
    ADD_MEMORIAL_MARKER: 'api/map/add-memorial-marker',
    DELETE_MEMORIAL_MARKER: 'api/map/delete-memorial',
    GET_MEMORIAL: 'api/map/get-memorial',
    EDIT_MEMORIAL: 'api/map/edit-memorial-marker',
    ADD_MEMORIAL_TYPE: 'api/map/add-memorial-type',
    EDIT_MEMORIAL_TYPE: 'api/map/edit-memorial-type',
    DELETE_MEMORIAL_TYPE: 'api/map/delete-memorial-type',
  },
  PUBLICATION: {
    ADD: 'api/publication/add',
    GET: 'api/publication/get',
    GET_ALL: 'api/publication/get-all',
    GET_FAVORITE: 'api/publication/get-favorite',
    GET_RECENT: 'api/publication/get-recent',
    DELETE: 'api/publication/delete',
    EDIT: 'api/publication/edit',
    SET_FAVORITE: 'api/publication/set-favorite',
    REMOVE_FAVORITE: 'api/publication/remove-favorite',
  },
  AUTH: {
    LOGIN: 'api/auth/login',
    LOGOUT: 'api/auth/logout',
    REFRESH: 'api/auth/refresh',
  },
};
